#undef TAPPING_TERM
#define TAPPING_TERM 175

#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 10

#define CAPS_LOCK_STATUS
#define SERIAL_NUMBER "VR6xY/eaapNy"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 3

#define TAPPING_TERM_PER_KEY
#define RGB_MATRIX_STARTUP_SPD 60

#define SELECT_WORD_OS_MAC
#define QUICK_TAP_TERM_PER_KEY

#define CUSTOM_SHIFT_KEYS_NEGMODS ~MOD_MASK_SHIFT